uses: ScholliYT/Broken-Links-Crawler-Action@v3
with:
  website_url: 'https://extendogs.github.io/DYAS/'
  exclude_url_prefix: 'mailto:,https://www.linkedin.com,https://linkedin.com'
  verbose: 'true'
  max_retry_time: 30
  max_retries: 5
  max_depth: 1
